---
- name: Install and configure MySQL on EC2 instance
  hosts: mysql_servers
  become: yes
  tasks:
    - name: Update apt-get and install necessary packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - mysql-server  # MySQL Server
        - python3-mysqldb  # MySQL Python library for Python 3.x

    - name: Start and enable MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Set MySQL root password
      mysql_user:
        name: root
        password: "your_root_password"
        host: "localhost"
        priv: '*.*:ALL,GRANT'
        state: present
