---
- name: Install and configure MySQL on EC2 instance
  hosts: mysql_servers
  become: yes
  tasks:
    - name: Update apt-get cache
      apt:
        update_cache: yes

    - name: Install MySQL server and Python MySQL library 
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - mysql-server  # MySQL Server
        - python3-mysqldb  # MySQL Python library for Python 3.x

    - name: Start and enable MySQL service
      service:
        name: mysql
        state: started
        enabled: yes
