---
- name: Install MySQL on EC2 instance
  hosts: mysql_servers
  become: yes
  tasks:
    - name: Update apt-get and install necessary packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - mysql-server  # MySQL Server
        - python3-mysqldb  # MySQL Python library for Python 3.x
        - mysql-client   # MySQL Client (optional but useful for management tasks)
        - libmysqlclient-dev  # MySQL development files (optional for certain applications)
        - python3-pip  # Python package installer (optional but useful for installing Python packages)

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes
