---
- name: MySQL Installation and Password Management
  hosts: mysql_servers
  become: yes
  vars:
    mysql_root_password: "your_actual_root_password_here"
  tasks:
    - name: Install MySQL server and Python MySQL libraries
      apt:
        name:
          - python3-PyMySQL
          - mysql
          - mysql-server
        state: present

    - name: Start the MySQL service
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: Ensure MySQL root password is set
      mysql_user:
        name: root
        host: "{{ item }}"
        password: "{{ mysql_root_password }}"
        priv: "*.*:ALL,GRANT"
        state: present
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

    - name: Copy .my.cnf file with root password credentials
      template:
        src: Ansible-Mysql-Github-Actions/.my.cnf
        dest: ./.my.cnf
        owner: root
        mode: '0600'
