---
- name: Install and configure MySQL on EC2 instance
  hosts: mysql_servers
  become: yes
  tasks:
    - name: Install debconf-utils
      apt:
        name: debconf-utils
        state: present
        update_cache: yes

    - name: Preconfigure MySQL root password
      debconf:
        name: "mysql-server"
        question: "mysql-server/root_password"
        value: "temp_password"
        vtype: "password"

    - name: Preconfigure MySQL root password again (for confirmation)
      debconf:
        name: "mysql-server"
        question: "mysql-server/root_password_again"
        value: "temp_password"
        vtype: "password"

    - name: Update apt-get and install necessary packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - mysql-server  # MySQL Server
        - python3-mysqldb  # MySQL Python library for Python 3.x

    - name: Start and enable MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Set MySQL root password with temporary script
      shell: |
        mysql -u root -ptemp_password -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'your_root_password'; FLUSH PRIVILEGES;"
      args:
        executable: /bin/bash

    - name: Ensure MySQL root password is secure
      mysql_user:
        name: root
        password: "your_root_password"
        host: "localhost"
        priv: '*.*:ALL,GRANT'
        state: present
      vars:
        ansible_mysql_login_user: root
        ansible_mysql_login_password: "your_root_password"
