---
- name: Simple MySQL Installation
  hosts: mysql_servers
  become: yes
  tasks:
    - name: Update apt-get
      apt:
        update_cache: yes

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Install Python MySQL libraries
      apt:
        name: python3-pymysql
        state: present

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Set MySQL root password if it is not already set
      ignore_errors: yes
      block:
        - name: Check if MySQL root password is set
          shell: |
            mysql -u root -e "SELECT 1;"
          register: mysql_root_password_check
          changed_when: false
          failed_when: false

        - name: Set MySQL root password
          mysql_user:
            name: root
            password: "your_root_password"
            host: "localhost"
            priv: "*.*:ALL,GRANT"
            state: present
            login_unix_socket: /var/run/mysqld/mysqld.sock
          when: mysql_root_password_check.rc != 0

    - name: Update MySQL root password if already set
      mysql_user:
        name: root
        password: "your_new_root_password"
        host: "localhost"
        priv: "*.*:ALL,GRANT"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
      when: mysql_root_password_check.rc == 0
      ignore_errors: yes
