---
- name: MySQL Installation on EC2 instance
  hosts: mysql_servers
  become: yes
  tasks:
    - name: Update apt-get
      apt:
        update_cache: yes

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Install Python MySQL libraries
      apt:
        name: python3-pymysql
        state: present

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Check if MySQL root password is already set
      shell: |
        mysql -u root -e "SELECT 1;"
      register: mysql_root_check
      ignore_errors: true

    - name: Set MySQL root password
      mysql_user:
        name: root
        password: "your_root_password"
        host: "localhost"
        priv: "*.*:ALL,GRANT"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
      when: mysql_root_check.rc != 0

    - name: Ensure root password is set
      mysql_user:
        name: root
        password: "your_root_password"
        host: "localhost"
        priv: "*.*:ALL,GRANT"
        state: present
        login_user: root
        login_password: "your_root_password"
        login_unix_socket: /var/run/mysqld/mysqld.sock
      when: mysql_root_check.rc == 0
