---
- name: MySQL Installation and Password Management
  hosts: mysql_servers
  become: yes
  vars:
    mysql_root_password: "your_actual_root_password_here"
  tasks:
    - name: Update apt-get
      apt:
        update_cache: yes

    - name: Install MySQL server and Python MySQL libraries
      apt:
        name:
          - mysql-server
          - python3-pymysql
        state: present

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Set MySQL root password
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        host: localhost
        priv: "*.*:ALL,GRANT"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
      ignore_errors: yes
      register: mysql_root_password_set

    - name: Update MySQL root password if already set
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        host: localhost
        priv: "*.*:ALL,GRANT"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
      when: mysql_root_password_set|failed

    - name: Check MySQL root password
      shell: mysql --user=root --password="{{ mysql_root_password }}" --execute="SELECT 1;"
      register: mysql_root_password_check
      ignore_errors: yes

    - name: Debug output
      debug:
        var: mysql_root_password_check

    - name: Fail if MySQL root password is incorrect
      fail:
        msg: "MySQL root password is incorrect or could not be set."
      when: mysql_root_password_check.rc != 0 and not mysql_root_password_set.changed
